### ISSUE TITLE
Add basic resources

### ISSUE THREAD

**Issue by axiomista** [NorthwestGreenChemistry/PrISM#10]
User can click to open resources to help with GQ

**Comment by drunkONdata** [comment]
Resource tab markdown files complete. Awaiting review and QC check by Amelia.

**Comment by AmeliaNestler** [comment]
Basic version: Add list of resources to the home page (e.g. below the generate report pdf button). So it would list out Chemical Inventory, Exposure Assessment, etc. 
In the future: Link the resources where they are mentioned in each step (e.g. on Production, it says "See Chemical Inventory" in the guiding questions - it should link to the resource there).

Also for basic: OK to just open it up on Github.
In the future: Render it in the app.

**Comment by mariannefeng** [comment]
I think adding a Resources menu item might be nice, they can select the resource title they're interested in from the menu and then view selected resource from there.

**Comment by AmeliaNestler** [comment]
Talking to some other people, it would be really great if they rendered in the app for v1 if possible.

**Comment by AmeliaNestler** [comment]
It's added as a menu, working on Mac and Windows! Woo!
