### ISSUE TITLE
Style Intro Page (Home.js) and Include Intro Markdown

### ISSUE THREAD

**Issue by halfnibble** [NorthwestGreenChemistry/PrISM#20]
The intro page, component Home.js, should look decent and include the Intro Markdown.

Refer to someone who created the Markdown to determine how it should be displayed.

**Comment by axiomista** [comment]
Picking this up now!

**Comment by axiomista** [comment]
In progress. This currently displays the `introduction.md` and still needs:

- [ ] Scroll bar
- [ ] Styles
- [ ] Clarity of navigation

**Comment by axiomista** [comment]
https://github.com/NorthwestGreenChemistry/PrISM/pull/46
