### ISSUE TITLE
Track Initial Open and Skip Intro Page

### ISSUE THREAD

**Issue by halfnibble** [NorthwestGreenChemistry/PrISM#21]
- [x] Track whether or not the app has been opened before

- [ ] If the app has been opened before, skip the landing page

- [x] Ideally, find a way to track on a "per machine" basis. (So if someone shares the app, it opens the intro page again).

**Comment by axiomista** [comment]
Added @mariannefeng because she was previously working on a config file where we may track if the app is being opened for the "first time" and may have ideas. :)

**Comment by axiomista** [comment]
@sjgllghr I checked the boxes! We will have to set 'opened' to false in an appropriate place after that and then we can close this task 🎉

**Comment by mariannefeng** [comment]
done, also added button to show intro again for reference. Styling could use some work though
