### ISSUE TITLE
Identify and import lib for PDF generation

### ISSUE THREAD

**Issue by axiomista** [NorthwestGreenChemistry/PrISM#4]

**Comment by halfnibble** [comment]
I am leaning towards pdfMake
[https://github.com/bpampuch/pdfmake](https://github.com/bpampuch/pdfmake)

**Comment by NorthDecoder** [comment]
Chose [jsPDF ](https://www.npmjs.com/package/jspdf) instead of pdfmake, working toward a first commit.

**Comment by axiomista** [comment]
https://github.com/NorthwestGreenChemistry/PrISM/commit/897393cd3b922c384b47a97602f68efd503c54ae
