### ISSUE TITLE
Create styles (CSS) and implement

### ISSUE THREAD

**Issue by axiomista** [NorthwestGreenChemistry/PrISM#5]
Work together with @AmeliaNestler to decide what looks best and fits Northwest Green Chemistry's theme

- Create local css for modal: text to black from white (global css)

**Comment by NorthDecoder** [comment]
Referencing neutral color [chart](https://www.somacon.com/p142.php) propose some off-white colors for tags `body`, `h2` and `a`, and make the `a` tag slightly larger, in file `app/app.global.css`
* body `color: #F6F9ED;`
* h2 `color: #FDF2EE;`
* a `color: #FEF6E4;`
  - `font-size: 110%;`

Reference [pen](https://codepen.io/NorthDecoder/pen/MPxZzG)
