### ISSUE TITLE
Transition from Steps 2 and 3 Info Modal

### ISSUE THREAD

**Issue by halfnibble** [NorthwestGreenChemistry/PrISM#54]
Display information prior to starting step 3.

Is it supposed to be a dismissible modal? I don't know.

**Comment by axiomista** [comment]
> Is it supposed to be a dismissible modal? I don't know.

We think so. ¯\_(ツ)_/¯

**Comment by AmeliaNestler** [comment]
For me to do - edit the markdown for step 3 to talk about how the chemical inventory is used multiple times and it may be worth checking out now in particular. Figure out if this note should be added elsewhere as well.

**Comment by AmeliaNestler** [comment]
Added to step 3, and now checking other steps.

**Comment by AmeliaNestler** [comment]
Added to steps 4, 5.
