### ISSUE TITLE
Product Lost?

### ISSUE THREAD

**Issue by NorthDecoder** [NorthwestGreenChemistry/PrISM#67]
Testing the downloaded PrISM msi file version PrISM.Setup.0.1.2-rc.exe

I created a new product in PrISM on 3-November and entered some data by answering questions.
Today I opened PrISM to look a that product and found that it is no longer in the product menu.

In what directory is the data being stored? 
Where did my test data go? ( and all that hard work I did to enter it 😺 )

**Comment by sjgllghr** [comment]
The data is being stored in localStorage. Did you do anything that might have cleared that?

A possible solution or way to potentially avoid this in the future might be implement #43.

**Comment by NorthDecoder** [comment]
Norton Security runs a File Cleanup of 'old' temporary files, and and so does the Windows 10 setting.
