### ISSUE TITLE
Collapsible sections in text?

### ISSUE THREAD

**Issue by AmeliaNestler** [NorthwestGreenChemistry/PrISM#84]
Figure out if you can do collapsible sections. If so, implement for examples or other areas.

**Comment by AmeliaNestler** [comment]
I tried this, and it didn't work. Anyone have other ideas on how to get it working? 

https://gist.github.com/joyrexus/16041f2426450e73f5df9391f7f7ae5f

I tested it in marked's demo and it worked fine (https://marked.js.org/demo/?text=&options=) and in github and it worked fine, but it doesn't work in the app.

**Comment by NorthDecoder** [comment]
I had to scan each of your commits to figure out which you were referring to, so for example I copied
the following from commit f4bf89c , and added the paragraph html tag `<p></p>` without newline directly after the `summary` tag and that sort of does the collapsing both in the react-markdown [demo](https://rexxars.github.io/react-markdown/) and here, with the knowledge that some of the markdown in the collapsed section does not work as noted in the above post.

----

<details><summary>Floral Soil</summary>
<p>
A product concept with exceptional ambitions for sustainable product design is [Floral Soil](https://www.floralsoilsolutions.com/). Floral Soil is designed to replace conventional floral foam used by florists to hold flowers in place in an arrangement and to keep them moist. The designer set out to create a product that was ‘safe enough to eat’ in addition to being biobased, biodegradable in home gardens or compost, reusable and high performing with respect to holding water to replace current floral foams.

![Floral Soil design goals includes: 1) Non-toxic, 2) Bio-based, 3) Biodegradable, 4) Grow seeds, 5) Hold water](https://raw.githubusercontent.com/NorthwestGreenChemistry/PrISM/develop/app/assets/1-design-goals/project-goals.png)

[Learn more about Floral Soil Solutions.](https://www.floralsoilsolutions.com/)
</p>
</details>

**Comment by AmeliaNestler** [comment]
I tried copying it in like you've written it here, and had the same issue. It's like the <> type tags aren't enabled maybe? I tried using one for an img so I could set width and it just showed up as text, too.

![image](https://user-images.githubusercontent.com/14830387/51933431-28615c00-23b6-11e9-8b10-febd4126a16f.png)

**Comment by mariannefeng** [comment]
Collapsible sections isn't widely supported by markdown, and will only work with certain markdown libraries. The one we're currently using does not support collapsible sections, it looks like the one you guys were linking is using this one: https://github.com/markedjs/marked. 

With a bit of finangling, we could swap over to the other library (I say with a bit of finangling because the library isn't a react library, so no promises on a smooth bug-less transition)

**Comment by NorthDecoder** [comment]
Also note there are different renderer's for testing in the browser, but the only one that matters is Chromium (NOT Google Chrome) which is what is used by ElectronJS in the app.

**Comment by AmeliaNestler** [comment]
OK, so it sounds like this isn't possible. At least not without some major changes, and I want to avoid those for now.
